defmodule Dryw.Repo.Migrations.CreateGigCymruIgdcPod360Reviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:gig_cymru_igdc_pod_360_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :reviewee_id,
          references(:users,
            column: :id,
            name: "reviewee_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :collaboration, :integer
      add :innovation, :integer
      add :inclusive, :integer
      add :excellence, :integer
      add :compassion, :integer

    end
  end

  def down do
    drop constraint(:appraisals, "appraisals_reviewer_id_fkey")

    drop constraint(:appraisals, "appraisals_reviewee_id_fkey")

    drop table(:gig_cymru_igdc_pod_360_reviews)
  end
end
