#!/bin/sh
set -euf

export App=Dryw
export app=drwy
export Dom=Accounts
export dom=accounts
export Resource=Item
export resource=item
export Resources=Items
export resources=items

mix ash.gen.resource \
    $App.$Dom.$Resource \
    --conflicts replace \
    --default-actions create,read,update,destroy \
    --extend postgres \
    --uuid-primary-key id \
    --relationship belongs_to:reviewer:$App.$Dom.User \
    --relationship belongs_to:reviewee:$App.$Dom.User \
    --attribute collaboration int \
    --attribute innovation int \
    --attribute inclusive int \
    --attribute excellence int \
    --attribute compassion int \

mix ash.codegen create_$resources
mix ash.migrate

mkdir -p test/$app/$dom
touch test/$app/$dom/$resource.ex

mkdir -p lib/${app}_web/live/$resources
touch lib/${app}_web/live/$resources/form_live.ex
touch lib/${app}_web/live/$resources/index_live.ex
touch lib/${app}_web/live/$resources/show_live.ex

mkdir -p test/${app}_web/live/$resources
touch test/${app}_web/live/$resources/form_test.ex
touch test/${app}_web/live/$resources/index_test.exs
touch test/${app}_web/live/$resources/show_test.exs

cat << EOF
Edit file lib/${app}_web/router.ex to add live routes:
live "/$resources", $Resources.IndexLive
live "/$resources/:id", $Resources.ShowLive
live "/$resources/:id/edit", $Resources.FormLive, :edit
EOF
